### ISSUE TITLE
No image on linux

### ISSUE THREAD

**Issue by pierrexn** [wang-bin/mdk-sdk#114]
I have some users on linux that have no image but audio when playing video files
Ive attached the log, do you have an idea?
[log.txt](https://github.com/wang-bin/mdk-sdk/files/12559815/log.txt)

**Comment by wang-bin** [comment]
`vaPutSurface` failed, don't know the reason, have to read libva source code. what about using xcb_egl?

**Comment by pierrexn** [comment]
which var should i set for?

**Comment by wang-bin** [comment]
QT_XCB_GL_INTEGRATION=xcb_egl

**Comment by pierrexn** [comment]
it works with xcb_egl

**Comment by wang-bin** [comment]
I have bug reports from other users, and this error exists in other projects, for example https://bbs.archlinux.org/viewtopic.php?pid=2079443#p2079443

Seems `vaPutSurface` always fails for `iHD_drv_video.so` driver. This is the answer from intel https://github.com/intel/media-driver/issues/1406#issuecomment-1537688086  You can run `xdpyinfo|grep DRI` to see if DRI2 is supported.  I think in your app you can first check DRI2 support, then enable xcb_egl if necessary.

**Comment by pierrexn** [comment]
ok thanks

**Comment by wang-bin** [comment]
I have tested vlc, kodi, gstream and mpv, none of them support 0-copy rendering in this case(glx instead of egl).

Now i provide a new solution in the latest sdk: texture from dri3 pixmap. It supports both x11 glx and egl. If `vaPutSurface` failed, dri3 pixmap will be tried. This requires video processing feature in libva driver, i.e. if `vainfo -a |grep VideoProc` is true, dri3 pixmap will work. I tested on an intel gpu which supports both iHD and i965 driver but none of these drivers supports `vaPutSurface`, run `apt install intel-media-va-driver-non-free` to install iHD driver fixes the issue with the latest sdk(opensource iHD driver from intel-media-va-driver lacks of VideoProc).
