### ISSUE TITLE
waitFor returns before the actual state is set

### ISSUE THREAD

**Issue by alexcristd** [wang-bin/mdk-sdk#53]
Hello,

This is a 2-part question/issue:
I need to query the video length (duration) of multiple files, without/before actually playing them. Like scanning through a playlist. Unless I've missed anything, the MDK SDK doesn't offer a direct way of doing this, other than simply preparing the file for playback.

1) This is the way I currently implemented it (QT5):
```c++
qint64 MdkPlayer::duration(const QString &filePath)
{
    m_internalPlayer->setMedia(filePath.toUtf8().data());
    m_internalPlayer->setActiveTracks(MediaType::Audio, {});
    m_internalPlayer->setActiveTracks(MediaType::Subtitle, {});
    m_internalPlayer->setBufferRange(0);
    m_internalPlayer->prepare();
    m_internalPlayer->waitFor(State::Paused);

    // FIXME: In case the video is almost empty (or maybe corrupt), loading the file seems to take longer than expected. For some reason, waitFor returns before the actual requested state is set. So we need to wait a bit more...
    if (m_internalPlayer->state() != State::Paused)
    {
        qDebug() << "Invalid state detected! Taking a nap, hopefully it will fix itself...";
        QThread::msleep(1000);
    }

    auto result = m_internalPlayer->mediaInfo().duration;

    m_internalPlayer->setMedia(nullptr);
    m_internalPlayer->set(State::Stopped);
    m_internalPlayer->waitFor(State::Stopped);

    return result;
}
```

Is this the most efficient way of getting the video duration, without actually playing the file? This method is called rapidly in a loop, for multiple files, while parsing a playlist. Or is there a more optimal way?

2) As you can see in the code above, there seems to be an issue with empty video files. The video files are valid, but are essentially empty (produced by a device that records continuously, files of a fixed duration, and these empty files can appear when recording is stopped exactly when a new file is started).

The ```waitFor``` method returns before the ```Paused``` state is actually set. (As a side note, the same thing happens for the next file after the ”broken” one as well, regardless of what file is next. But after that, things go back to normal). Without that workaround, the code crashes because the metadata is not available yet.
Usually a 500-1000 ms wait avoids a crash, and the correct state is set and the metadata is available. But this is a hack that can't really be trusted on the long term.

I've posted a sample file here: https://drive.google.com/file/d/1xUU9i9sRa5-1edz4YNPTqRRBvzfAp57-/view?usp=sharing

Thanks!

**Comment by cristiandragusanu** [comment]
Thanks, the suggested example work without any workarounds. :)

As for the original question, it doesn't impact me anymore, but it's still weird that waitFor returned with a different state than the one requested for. I would expect to wait until the set timeout exceeds.

Also, it's still weird that, after waitFor returns (Paused or Stopped, regardless), the mediaInfo is not ready yet, but it is ready a few ms later. I would expect at least that info to be in a consistent state.

And the 3rd weird thing, is that the same thing happens for the next file (following the ”broken” file), even if the next file is a perfectly valid one.

Maybe it has a lower priority right now, since probably is not a usual scenario, but still. :)

**Comment by wang-bin** [comment]
> As for the original question, it doesn't impact me anymore, but it's still weird that waitFor returned with a different state than the one requested for. I would expect to wait until the set timeout exceeds.

because state changes in another thread. you can use `onStateChanged()`

> Also, it's still weird that, after waitFor returns (Paused or Stopped, regardless), the mediaInfo is not ready yet, but it is ready a few ms later. I would expect at least that info to be in a consistent state.

To read mediainfo without playback, use the example i mentioned, resources will be released ASAP.  For playback, the example is https://github.com/wang-bin/mdk-examples/blob/master/Native/offscreen.cpp#L23 , the callback of `onMediaStatusChanged()` does not change playback state.

**Comment by wang-bin** [comment]
`waitFor(State::Paused)` should be fixed in the latest build
